name: Feature request
description: Propose a new feature or improvement
title: "Feature: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Suggest a feature that improves Browser Switch for real-world daily use.

        Please describe the user problem first, then your proposed solution. Product language is fine; implementation details are optional.

  - type: textarea
    id: problem_or_use_case
    attributes:
      label: Problem or use case
      description: What are you trying to do that Browser Switch does not support well today?
      placeholder: "When I am switching between work and personal browser contexts..."
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
      description: What behavior or UI would you like to see?
    validations:
      required: true

  - type: textarea
    id: alternatives_considered
    attributes:
      label: Alternatives considered (optional)
      description: Workarounds or other approaches you considered.

  - type: dropdown
    id: feature_area
    attributes:
      label: Feature area
      options:
        - Browser switching
        - Menu bar UI / menu behavior
        - Network / VPN context
        - Power tools (Option key features)
        - Run on Startup / settings
        - Build / packaging / installation
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: ui_impact
    attributes:
      label: Does this change the UI or menu behavior?
      options:
        - "No"
        - "Yes"
        - Not sure
    validations:
      required: true

  - type: textarea
    id: success_criteria
    attributes:
      label: What would success look like?
      description: Define the expected outcome (acceptance criteria if you have them).
      placeholder: |
        - I can ...
        - The menu shows ...
        - The action completes without opening System Settings
    validations:
      required: true

  - type: checkboxes
    id: pre_submit_checks
    attributes:
      label: Before submitting
      options:
        - label: I searched existing issues and feature requests.
          required: true
        - label: I understand Browser Switch targets macOS 14+.
          required: true
